# -*- coding: utf-8 -*-
"""recommender_function.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QCdMpFY2ZFDDWTm_iZmUb_GlWhf2HEYH
"""

# load and evaluate a saved model
from numpy import loadtxt
from keras.models import load_model
import numpy as np
import pandas as pd
# load model
model = load_model('model.h5')

# summarize model
# model.summary()

df = pd.read_csv('https://raw.githubusercontent.com/Lambda-Spotify-Song-Suggester-3/datascience/master/kaggle_data/encoded.csv')

## Predictor function
def epic_predictor(input_track_key):
  '''
  This function takes in a 'track_key' which is a number from 0 to 3771.
  The function returns a list of ten numbers that are the "track_key"s of the
  dataframe imported above.
  '''
  song_data = np.array(list(df.track_key))
  artist = np.array([input_track_key for i in range(len(song_data))])


  predictions = model.predict([artist, song_data])
  predictions = np.array([a[0] for a in predictions])
  recommended_song_ids = (-predictions).argsort()[:10]

  # return a dataframe with only the ten most similar tracks

  ten_similar_tracks = df[df["track_key"].isin(recommended_song_ids)]
  
  # This is an option if you want to return a json string with all the attributes of the data
  #json_string = ten_similar_tracks.to_json(orient= 'table')
  #return json_string

  #But we are just giving you a list of the track_keys
  return ten_similar_tracks['track_key'].tolist()

##Testing the predictor
#epic_predictor(777)
